package servers

import javax.inject.{Inject, Singleton}
import play.api.db.Database

import scala.concurrent.Future
import anorm._

@Singleton
class InitDB @Inject() (db: Database, databaseExecutionContext: DatabaseExecutionContext) {

  //criar as tabelas
  db.withConnection { implicit con =>{

      val buscaInit: Boolean = SQL(
      """
          CREATE TABLE IF NOT EXISTS busca (
              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              linguagem VARCHAR (250),
              numero Integer,
              data TIMESTAMP
          );
          """
      ).execute();

      val repositorioInit: Boolean = SQL(
        """
            CREATE TABLE IF NOT EXISTS repositorio (
                id integer,
                nome VARCHAR (250),
                posicao integer,
                url VARCHAR (250),
                estrelas integer,
                busca_id integer,
                FOREIGN KEY (busca_id) REFERENCES busca(id)
            );
            """
      ).execute()

      println("[BD] busca")
      println("[BD] repositorio")
    }}

}
